# Generated by Django 4.0.1 on 2022-03-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lead_age_lead_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='age',
            field=models.IntegerField(),
        ),
    ]
